AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating an EC2 instance.
Parameters:
  UbuntuAmiId:
    Type: String
    Description: The AMI ID for the Ubuntu instance
Resources:
  FulaInternetGateway:
    Type: AWS::EC2::InternetGateway
  FulaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
  FulaRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref FulaVPC
  FulaVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FulaVPC
      InternetGatewayId: !Ref FulaInternetGateway

  FulaRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref FulaRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref FulaInternetGateway
  FulaSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref FulaSubnet
      RouteTableId: !Ref FulaRouteTable
  FulaSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FulaVPC
      CidrBlock: 10.0.0.0/24
  FulaEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.2xlarge
      ImageId: !Ref UbuntuAmiId  # Replace with the AMI ID for Ubuntu 22.04 64-bit in your region
      KeyName: functionland  # Replace with the name of your existing key pair
      Tags:
        - Key: Name
          Value: fula-pool
        - Key: Group
          Value: pools
      NetworkInterfaces:
        - DeviceIndex: '0'
          AssociatePublicIpAddress: true
          SubnetId: !Ref FulaSubnet
          GroupSet:
            - !Ref FulaSecurityGroup

  FulaSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: fula-node
      GroupDescription: Security Group for Fula Node
      VpcId: !Ref FulaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0

  FulaVolume:
    Type: AWS::EC2::Volume
    Properties: 
      Size: 30
      AvailabilityZone: !GetAtt 
        - FulaEC2Instance
        - AvailabilityZone
      VolumeType: gp2

  FulaVolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties: 
      InstanceId: !Ref FulaEC2Instance
      VolumeId: !Ref FulaVolume
      Device: /dev/sdh